project_id = "fqzarmpveffjoccovysy"

[functions.create-property]
verify_jwt = false

[functions.submit-review]
verify_jwt = false

[functions.pet-assistant]
verify_jwt = false

[functions.notify-contact-message]
verify_jwt = false

[functions.bulk-create-properties]
verify_jwt = false

[functions.notify-property-reported]
verify_jwt = false